# Generated by Django 5.2.7 on 2025-10-15 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение')),
                ('question_type', models.CharField(choices=[('single', 'Один верный ответ'), ('multiple', 'Несколько верных ответов'), ('text', 'Короткий текстовый ответ'), ('long_text', 'Развёрнутый ответ'), ('number', 'Числовой ответ'), ('order', 'Упорядочивание')], max_length=20, verbose_name='Тип вопроса')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Баллы за вопрос')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные параметры')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='Текст варианта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/', verbose_name='Изображение')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('max_warnings', models.PositiveIntegerField(default=3, verbose_name='Максимум предупреждений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('show_answers', models.BooleanField(default=False, verbose_name='Показывать ответы после прохождения')),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Доступные группы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='UserTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало прохождения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('tab_switches', models.PositiveIntegerField(default=0, verbose_name='Переключения вкладок')),
                ('time_outside_seconds', models.PositiveIntegerField(default=0, verbose_name='Время вне вкладки (сек)')),
                ('last_left_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний выход')),
                ('submitted_due_to_violation', models.BooleanField(default=False, verbose_name='Завершён из-за нарушения')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Последний сигнал клиента')),
                ('client_token', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Токен клиента')),
                ('score_percent', models.FloatField(blank=True, null=True, verbose_name='Процент правильных ответов')),
                ('earned_points', models.FloatField(blank=True, null=True, verbose_name='Набрано баллов')),
                ('total_points', models.FloatField(blank=True, null=True, verbose_name='Всего баллов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия прохождения теста',
                'verbose_name_plural': 'Сессии прохождения тестов',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('order_answer', models.JSONField(blank=True, default=list, null=True, verbose_name='Порядок элементов')),
                ('points_scored', models.FloatField(blank=True, null=True, verbose_name='Полученные баллы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос')),
                ('selected_options', models.ManyToManyField(blank=True, to='tests.answeroption', verbose_name='Выбранные варианты')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.usertestsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
