# Generated by Django 5.2.7 on 2025-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_warnings',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='client_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
