# Generated by Django 5.2.7 on 2025-10-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50, verbose_name='Оценка')),
                ('min_percent', models.FloatField(verbose_name='Минимальный процент')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем выше оценка.', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-order'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='show_grade',
            field=models.BooleanField(default=False, verbose_name='Отображать оценку'),
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.grade', verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название системы')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_system', to='auth.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Система оценивания',
                'verbose_name_plural': 'Системы оценивания',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='grading_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tests.gradingsystem', verbose_name='Система оценивания'),
        ),
    ]
