# Generated by Django 5.2.7 on 2025-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_max_warnings_usertestsession_client_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestsession',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='score_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
