# Generated by Django 5.2.7 on 2025-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tests', '0002_grade_test_show_grade_usertestsession_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingsystem',
            name='group',
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='groups',
            field=models.ManyToManyField(related_name='grading_systems', to='auth.group', verbose_name='Группы'),
        ),
    ]
