# Generated by Django 5.2.7 on 2025-10-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_usertestsession_is_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usertestsession',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='test',
            name='num_questions_per_topic',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='topics',
            field=models.ManyToManyField(related_name='tests', to='tests.topic'),
        ),
    ]
