# Generated by Django 5.2.7 on 2025-10-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_topic_remove_usertestsession_is_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='test',
            name='num_questions_per_topic',
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
