# Generated by Django 5.2.7 on 2025-10-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tests', '0005_remove_test_topics_remove_question_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
