# Generated by Django 5.2.7 on 2025-10-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestsession',
            name='is_submitted',
        ),
    ]
