# Generated by Django 5.2.7 on 2025-10-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_usertestsession_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='google_course_id',
            field=models.CharField(blank=True, help_text='ID курса в Google Classroom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='google_coursework_id',
            field=models.CharField(blank=True, help_text='ID задания в Google Classroom', max_length=100, null=True),
        ),
    ]
