# Generated by Django 5.2.7 on 2025-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_test_google_course_id_test_google_coursework_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestsession',
            name='google_student_submission_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
