# Generated by Django 5.2.7 on 2025-10-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_usertestsession_google_student_submission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='google_course_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='google_coursework_id',
        ),
    ]
